import Provider from "@/components/Provider";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { getProfileUrl } from "@/actions/actions";
import Footer from "@/components/Footer"
import { Toaster } from "@/components/ui/toaster";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}) {
  const session = await getServerSession(authOptions);
  const profileUrl = await getProfileUrl(session?.user.userId);

  return (
    <html lang="en">
      <Provider>
          <body className="font-primary flex flex-col h-screen justify-between items-center">
            <div className="bg-inherit w-full">
              <NavBar profilePicUrl={profileUrl} />
              {children}
            </div>
            <Toaster />
            <Footer />
          </body>
      </Provider>
    </html>
  );
}
