import type { Metadata } from "next";
import Provider from "@/components/Provider";
import NavBar from "@/components/NavBar";
import QueryProvider from "@/components/QueryProvider";
import Like from "@/models/Like";
import Comment from "@/models/Comment";
import User from "@/models/User";
import Post from "@/models/Post";
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Provider>
        <QueryProvider>
          <body className="font-primary flex flex-col h-screen justify-between items-center">
            <NavBar />
            {children}
          </body>
          </QueryProvider>
          <Footer />
      </Provider>
    </html>
  );
}
